config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'
  
  resources :users, only: [:index, :show]
  #resources :likes, only: [:destroy]
  resources :posts, only: [:index, :show, :create] do
    resources :likes, only: [:create, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # user -> posts
  has_many :posts, dependent: :destroy

  # user -> likes
  has_many :likes, dependent: :destroy

  # user -> likes -> posts
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id]) 
    Like.create(user_id: current_user.id, post_id: params[:post_id])
    render "posts/likes/create.js.erb"
  end

  def destroy
    @post = Post.find(params[:post_id])
    Like.find_by(user_id: current_user.id, id: params[:id]).destroy
    render "posts/likes/destroy.js.erb"
  end

  def show
    render partial: "posts/like", locals: { post: post}
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IineAppTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_like.html.erb
<% if current_user.already_liked?(post) %>
  <td><%= link_to "いいねを外す", post_like_path(post, post.likes.find_by(user_id: current_user.id)), method: :DELETE, remote: true %>(<%= post.liked_users.count %>)</td>
<% else %>
  <td><%= link_to "いいね", post_likes_path(post), method: :POST, remote: true %>(<%= post.liked_users.count %>)</td>
<% end %>

app/views/posts/index.html.erb
<h1>いいねサンプル</h1>
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
  <h2>投稿する</h2>
  
  <%= form_with model: @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :body %>
    <%= f.text_field :body %>
    <br>
    <% # <button>Submit</button> %>
    <%= f.submit %>
  <% end %>

  <hr>
  <h2>投稿一覧</h2>
  <% @posts.each do |post| %>
    <a href="/users/<%= post.user.id %>"><%= post.user.email %></a>
    <a href="/posts/<%= post.id %>"><%= post.title %></a>
    <br>
    <a href="/posts/<%= post.id %>"><%= post.body %></a>
    <br>

    <% # likes button %>
    <div id="likes_buttons_<%= post.id %>">
        <%= render partial: "posts/like", locals: { post: post} %>
    </div>
    <br>
    <br>
  <% end %>
<% end %>
   <p>テスト</p>

  <%= link_to "ユーザー登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>

 

app/views/posts/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'posts/like', locals: { post: @post}) %>");

app/views/posts/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'posts/like', locals: { post: @post }) %>");

app/views/posts/show.html.erb
<h1>投稿詳細ページ</h1>
<h3><%= @post.user.email %></h3>
<h3><%= @post.title %></h3>
<h3><%= @post.body %></h3>
<h3>いいね件数: <%= @post.likes.count %></h3>
<% if current_user.already_liked?(@post) %>
  <td><%= link_to "いいねを外す", like_path(@post.likes.find_by(user_id: current_user.id)), method: :DELETE, remote: true %></td>
  (<%= @post.liked_users.count %>)
<% else %>
  <td><%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true %></td>
  (<%= @post.liked_users.count %>)
<% end %>
<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "ホームへ戻る", posts_path %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.email %></a>
  <hr>
<% end %>
<%= link_to "ホームへ戻る", posts_path %>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>
<h3><%= @user.email %></h3>
<h2>投稿内容</h2>
<% @user.posts.each do |post| %>
  <a href="/posts/<%= post.id %>"><%= post.body %></a>
  <hr>
<% end %>
<h3>いいねしている投稿</h3>
<% @user.liked_posts.each do |post| %>
  <%= post.user.email %>
  <%= post.body %>
<% end %>
<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "ホームへ戻る", posts_path %>